### PR TITLE
Adds tests

### PR DESCRIPTION
**Pull request by oke-aditya**
Let's test the model first if it is instantiating and abe to infer on random image.

Later we can create simple detection class and train

### CODE REVIEW

**Comment by oke-aditya** [comment]
There are some undefined variables @justusschock I have no clue what to do with them, please have a look

**Comment by oke-aditya** [comment]
Small error. @justusschock 
```
E   ModuleNotFoundError: No module named 'rising'
```

Can we copy paste the required function and refactor? When shifting to bolts we would probably not be using `rising`.

**Comment by justusschock** [comment]
Let's do that later. For now, we should just get a working version. I'll push my fixes later

**Comment by oke-aditya** [comment]
Almost there, Please squash and merge the PR !

**Comment by oke-aditya** [comment]
@justusschock 
I manually ran tests on my laptop and it seems there are errors in other tests, for now, the forward pass through the model is working.

Let's squash merge this PR and continue the next bug fixes in a fresh one

**Pull request merged**
